-- ==============================================================================
-- The Graticule Academic Geography Journal - Supabase Cloud Database Schema
-- Queen's University Belfast • Geography Society
-- ==============================================================================

-- 1. Authors Table
CREATE TABLE IF NOT EXISTS authors (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  affiliation TEXT,
  bio TEXT,
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Posts Table (Articles, Essays, and Cartographic Dispatches)
CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  date TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  cover_image TEXT,
  author TEXT NOT NULL,
  categories TEXT[] DEFAULT '{}',
  read_time TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Submissions Table (Manuscripts submitted via /contact/ portal)
CREATE TABLE IF NOT EXISTS submissions (
  id SERIAL PRIMARY KEY,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL,
  affiliation TEXT,
  article_title TEXT NOT NULL,
  category TEXT NOT NULL,
  abstract TEXT,
  file_name TEXT,
  file_size TEXT,
  status TEXT DEFAULT 'pending_review',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;

-- 5. Public Policies (Allow read access to published journals, allow submission write)
CREATE POLICY "Allow public read access on authors" ON authors FOR SELECT USING (true);
CREATE POLICY "Allow public read access on posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Allow public insert on submissions" ON submissions FOR INSERT WITH CHECK (true);

-- Allow full access for anon/authenticated API role during development & admin editing
CREATE POLICY "Allow all on authors for anon" ON authors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on posts for anon" ON posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow select on submissions for anon" ON submissions FOR SELECT USING (true);

-- 6. Indexes for Fast Filtering & Queries
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_date ON posts(date);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON submissions(created_at);

-- ==============================================================================
-- 7. Seed Initial Data (Authors & 47 Published Research Dispatches)
-- ==============================================================================

-- Seed Authors
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Emma Denton', 'Emma Denton', 'Undergraduate Geography Contributor & Arctic Expedition Fellow', 'School of Natural and Built Environment, Queen''s University Belfast', 'Emma Denton is an undergraduate geography student at Queen''s University Belfast who participated in an international scientific expedition to the High Arctic.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('The Graticule', 'The Graticule', 'Editorial Board Dispatch', 'QUB Geography Society • Queen''s University Belfast', 'Official editorial dispatches, investigative interviews, and collaborative research articles prepared by The Graticule Editorial Board.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Emma Hayes', 'Emma Hayes', 'BSc Geography Researcher (Soils & Remote Sensing)', 'School of Natural and Built Environment, Queen''s University Belfast', 'Emma Hayes conducts research in physical geography, agricultural soil science, and LiDAR-based riverbank erosion monitoring.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Zara Logan', 'Zara Logan', 'Contributing Author in Arctic Geopolitics', 'QUB Geography Society • Queen''s University Belfast', 'Zara Logan writes on circumpolar security, High North maritime governance, and Norwegian-Russian territorial tensions in Svalbard.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Courtney Mundt', 'Courtney Mundt', 'PhD Researcher in Archaeology & Paleoecology', 'School of Natural and Built Environment, Queen''s University Belfast', 'Courtney Mundt is a doctoral researcher analysing spatial distributions, origins, and folklore surrounding Irish cillíní burial sites.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Vincenzo Poti', 'Vincenzo Poti', 'Contributing Author in Political Geography & Geoengineering', 'School of Natural and Built Environment, Queen''s University Belfast', 'Vincenzo Poti investigates technopolitics, earth systems engineering, and the geopolitical implications of solar radiation management.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Erin Manson', 'Erin Manson', 'Undergraduate Geography Contributor', 'QUB Geography Society • Queen''s University Belfast', 'Erin Manson reflects on spatial pedagogy, student cohort experiences, and transitioning into university geography during unprecedented times.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Estelle Lowry', 'Dr Estelle Lowry', 'Research Fellow in Health Geography', 'School of Natural and Built Environment, Queen''s University Belfast', 'Dr Estelle Lowry is a Research Fellow at QUB investigating holistic human health, therapeutic landscapes, and physical-social environment linkages.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Dr Estelle Lowry', 'Dr Estelle Lowry', 'Research Fellow in Health Geography', 'School of Natural and Built Environment, Queen''s University Belfast', 'Dr Estelle Lowry is a Research Fellow at QUB investigating holistic human health, therapeutic landscapes, and physical-social environment linkages.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Naomi Duncan-Todd', 'Naomi Duncan-Todd', 'Lead Editor (2021/22), The Graticule', 'BSc Geography Researcher • Queen''s University Belfast', 'Naomi Duncan-Todd served as Lead Editor of The Graticule, writing extensively on environmental governance, freshwater ecology, and faculty research.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Yazmin Bleakley', 'Yazmin Bleakley', 'Contributing Author in Political & Economic Geography', 'QUB Geography Society • Queen''s University Belfast', 'Yazmin Bleakley explores critical Marxist geographical perspectives, global wealth distribution, and structural inequality.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Dónal Houston', 'Dónal Houston', 'Contributing Author in Historical & Mega-Engineering Geography', 'QUB Geography Society • Queen''s University Belfast', 'Dónal Houston investigates 20th-century geopolitical utopian engineering projects including Herman Sörgel''s Atlantropa Mediterranean dam scheme.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Dion Hughes', 'Dion Hughes', 'Editor & Contributor, The Graticule', 'School of Natural and Built Environment, Queen''s University Belfast', 'Dion Hughes is an editor specializing in feminist geography, ludonarrative spatial theory, and critical historical space exploration.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Julia Anusiak', 'Julia Anusiak', 'Staff Writer & Political Geography Contributor', 'The Graticule • Queen''s University Belfast', 'Julia Anusiak writes on urban peace-line segregation, climate diplomacy, and introductory human geography concepts.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Amy Oke', 'Amy Oke', 'Lead Editor, The Graticule', 'School of Natural and Built Environment, Queen''s University Belfast', 'Amy Oke is Lead Editor of The Graticule, focusing on cultural geographies of outer space, celestial cartography, and academic interviews.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Sasha Wilson', 'Sasha Wilson', 'Editor & Digital Media Contributor', 'BSc Geography Researcher • Queen''s University Belfast', 'Sasha Wilson covers marine conservation, Great Barrier Reef coral bleaching, and undergraduate fieldwork dispatches.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Jonathan Warke', 'Jonathan Warke', 'Contributing Author in Geographical Theory', 'QUB Geography Society • Queen''s University Belfast', 'Jonathan Warke explores geographic ideology, spatial transgression theory, and the history of utopian spatial planning.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Alysha Murray', 'Alysha Murray', 'BSc Geography Researcher (Arctic Marine Radioactivity)', 'School of Natural and Built Environment, Queen''s University Belfast', 'Alysha Murray conducts undergraduate dissertation research on radioactive waste contamination in the Russian Arctic Ocean.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Aimee Kielt', 'Aimee Kielt', 'Contributing Author in Social & Census Geography', 'QUB Geography Society • Queen''s University Belfast', 'Aimee Kielt analyses demographic classification, ethnic representation, and Polish diaspora inclusion in the Northern Ireland Census.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Shauna Vallely', 'Shauna Vallely', 'Contributing Author in Hydro-Geopolitics', 'QUB Geography Society • Queen''s University Belfast', 'Shauna Vallely examines Middle Eastern transboundary water governance, riparian conflict, and Jordan River geopolitics.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Emilia Coady-Booth', 'Emilia Coady-Booth', 'Contributing Author in History of Geography', 'QUB Geography Society • Queen''s University Belfast', 'Emilia Coady-Booth researches pioneering Victorian geographers, travel writing, and the legacy of Isabella Bird Bishop, FRGS.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Megan O''Kane', 'Megan O''Kane', 'PhD Researcher in Digital Geographies', 'School of Natural and Built Environment, Queen''s University Belfast', 'Megan O''Kane is a doctoral researcher exploring apocalyptic landscapes, environmental storytelling, and spatiality in video games.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Eliza O''Gorman', 'Eliza O''Gorman', 'Contributing Author in Resource Geopolitics', 'QUB Geography Society • Queen''s University Belfast', 'Eliza O''Gorman studies extractive economies, conflict mineral supply chains, and political geography in post-colonial West Africa.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Ciara McKnight', 'Ciara McKnight', 'BSc Geography with French Graduate & Volcanology Researcher', 'School of Natural and Built Environment, Queen''s University Belfast', 'Ciara McKnight conducted undergraduate dissertation field research on lava tube morphology and basalt cave microclimates in Iceland.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Amy Lally', 'Amy Lally', 'QUADRAT DTP PhD Researcher in Glacial Geomorphology', 'School of Natural and Built Environment, Queen''s University Belfast', 'Amy Lally is a NERC QUADRAT PhD researcher mapping glacial landforms and moraine dynamics at Breiðamerkurjökull, Iceland.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;
INSERT INTO authors (id, name, title, affiliation, bio, avatar) VALUES ('Martha Roney', 'Martha Roney', 'Contributing Author in Cultural & Urban Geography', 'QUB Geography Society • Queen''s University Belfast', 'Martha Roney explores urban morphology, heritage perception, and town-versus-gown spatial dynamics in historic university cities.', NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, affiliation = EXCLUDED.affiliation, bio = EXCLUDED.bio, avatar = EXCLUDED.avatar;

-- Seed Posts
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('a-journey-to-the-arctic', 'A Journey to the Arctic', '', '2021-04-07T10:00:24.419Z', 'A fellow QUB Geography student, Emma Denton, had the privilege of joining an expedition to the Arctic with the Students on Ice Foundation (SOI). She recently spoke to an audience at the Royal Geographic Society about her experience, and now, is providing The Graticule with an account of  her journey and escapade to Greenland and Nunavut, Canada.In the summer of 2019, I was lucky enough to join an expedition to the Arctic with the Students on Ice Foundation (SOI). SOI is an organisation offering ', '', 'https://static.wixstatic.com/media/c7bda6_271ccb734fa540c5b0516990c901e360~mv2.jpg/v1/fill/w_1000,h_750,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_271ccb734fa540c5b0516990c901e360~mv2.jpg', 'Emma Denton', ARRAY['Physical Geography & Glaciology', 'Climate Change & Environmental Systems']::TEXT[], '5 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('a-geographical-analysis-of-fordlândia', 'A Geographical Analysis of Fordlândia', '', '2021-06-23T16:27:45.526Z', 'This article was originally an essay-style assignment which aimed to critically analyse a ''current affairs'' article. The themes which were explored in the above mentioned article, whilst not directly acknowledged by the author, were post-colonialism and utopia; or more so a sense of a failed utopia on Henry Ford’s behalf. The article itself lacked any geographical analysis of the themes mentioned, thus the purpose of this article is to analyse the article and link it to appropriate themes and id', '', 'https://static.wixstatic.com/media/c7bda6_ce8fb5165ad3452fbeab0c063405f11c~mv2.jpg/v1/fill/w_672,h_448,al_c,lg_1,q_80/c7bda6_ce8fb5165ad3452fbeab0c063405f11c~mv2.jpg', 'The Graticule', ARRAY['Cultural & Historical Geography', 'Development Geographies']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('quantifying-the-degree-of-in-field-variability-in-soil-nutrient-content', 'Quantifying the Degree of In-Field Variability in Soil Nutrient Content ', '', '2021-04-09T14:00:18.365Z', 'Soil analysis is a vital component of nutrient management and its purpose is to assess the status of available nutrients for crop growth and monitor any changes in nutrient status due to agricultural practices. This is necessary to ensure optimum agricultural productivity and to reduce the incidence of nutrient transfer to waterways and other ecological zones. Regular soil analysis on a period of every 3-5 years is recommended (PDA, 2011). Agricultural practises are a major contributor to poor w', '', 'https://static.wixstatic.com/media/c7bda6_4a65670acd4a4fa2a94111740e2b5456~mv2.jpg/v1/fill/w_900,h_507,al_c,q_85/c7bda6_4a65670acd4a4fa2a94111740e2b5456~mv2.jpg', 'Emma Hayes', ARRAY['Soil Science & Agriculture', 'Physical Geography & Glaciology']::TEXT[], '7 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-cold-edge-of-the-arctic-norwegian-and-russian-tensions-concerning-svalbard', 'The ''Cold Edge'' of the Arctic: Norwegian and Russian Tensions Concerning Svalbard.', '', '2021-03-10T10:23:22.690Z', 'Arctic Geopolitics: “The battle for the High North has begun” (trans.) (Labévière &amp; Thual. 2008. 1)The Arctic’s location between the continents of North America, Europe and Asia made it an arena for geopolitical aggressions throughout the Cold War before the High North slipped into the academic periphery (Østreng. 2013; Østerud &amp; Hønneland. 2014). Climate change has, however, brought it back into the vanguard of International Relations (IR) (Østerud &amp; Hønneland. 2014). The Arctic’s average tempe', '', 'https://static.wixstatic.com/media/c7bda6_91ee16ebaf3448c8b5a79cab8100d6c9~mv2.jpg/v1/fill/w_1000,h_667,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_91ee16ebaf3448c8b5a79cab8100d6c9~mv2.jpg', 'Zara Logan', ARRAY['Political Geography & Geopolitics', 'Physical Geography & Glaciology']::TEXT[], '14 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-locations-origins-and-influences-behind-cillíní-an-overview-of-a-phd-dissertation-project', 'The Locations, Origins and Influences behind Cillíní: An Overview of a PhD Dissertation Project', '', '2023-09-11T10:59:09.393Z', 'My name is Courtney Mundt, and I am a PhD researcher in Archaeology and Paleoecology.  My dissertation involves analysing the locations, origins and influences behind cillíní (unconsecrated children’s burial grounds) in Counties Fermanagh, Meath and Antrim. I am using GIS and government resources to analyse the Ordnance Survey (OS) maps and read through the OS, archival and folklore documents to confirm and find sites. I am researching the socio-economic-religious influences behind cillíní origi', '', 'https://static.wixstatic.com/media/c7bda6_a0a3469846a84ef29014d02229547639~mv2.jpg/v1/fill/w_1000,h_750,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_a0a3469846a84ef29014d02229547639~mv2.jpg', 'Courtney Mundt', ARRAY['Cultural & Historical Geography', 'Irish Landscapes', 'Geographical Methods & Fieldwork']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-deus-and-the-machina-the-political-materiality-of-geoengineering', 'The Deus and the Machina: The Political Materiality of Geoengineering', '', '2023-10-02T20:39:18.594Z', 'This article analyses the technopolitics of geoengineering as a potential solution to climate change.  ', '', 'https://static.wixstatic.com/media/c7bda6_8d9acff55f43440eab27ccf69455b29e~mv2.jpg/v1/fill/w_768,h_480,al_c,q_85/c7bda6_8d9acff55f43440eab27ccf69455b29e~mv2.jpg', 'Vincenzo Poti', ARRAY['Political Geography & Geopolitics', 'Climate Change & Environmental Systems']::TEXT[], '17 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('tutorials-in-the-kitchen-the-experience-of-starting-university-in-2020', 'Tutorials in the Kitchen: The Experience of Starting University in 2020', '', '2021-02-03T10:00:24.115Z', 'Starting the first year of my undergraduate geography degree, I knew to expect a large jump from sixth form to university; different paces of working, different methods of study and a new way of socialising too. The change was indeed huge, however rather than being the typical university experience, the chasm of difference was caused by the Covid-19 pandemicThe transition to online study has been a challenge for most. For me as a first year, it meant not just having to cope with the expected wor', '', '', 'Erin Manson', ARRAY['Student Dispatches']::TEXT[], '3 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('health-geography-a-brief-overview', 'Health Geography: A Brief Overview ', '', '2023-10-27T11:43:59.960Z', 'In this article, a Research Fellow at QUB, Dr Estelle Lowry, provides us with a brief overview of health geography', '', 'https://static.wixstatic.com/media/c7bda6_2e65943cd5324578966785f6be10b737~mv2.jpg/v1/fill/w_700,h_330,al_c,lg_1,q_80/c7bda6_2e65943cd5324578966785f6be10b737~mv2.jpg', 'Dr Estelle Lowry', ARRAY['Health & Medical Geography']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('biodiversity-in-the-marine-world', 'Endangered Environments: Part 1-The Marine World', '', '2023-05-30T21:56:22.263Z', 'This article explores the main threats to aquatic biodiversity and the importance of the marine ecosystems ', '', 'https://static.wixstatic.com/media/c7bda6_dff9416e167848acbf0251134c1e66df~mv2.webp/v1/fill/w_1000,h_664,al_c,q_85/c7bda6_dff9416e167848acbf0251134c1e66df~mv2.webp', 'Naomi Duncan-Todd', ARRAY['Biogeography & Marine Ecology', 'Climate Change & Environmental Systems']::TEXT[], '8 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('marxism-and-global-poverty', 'Marxism and Global Poverty ', '', '2021-05-05T10:01:42.325Z', ' Marxism is a political theory founded on the works of Karl Marx that seeks to explain the negative effects of capitalism and how it has impacted upon labour, workers, and economic development (Investopedia, 2019). As a theory, Marxism can successfully explain global poverty, defined as “the number of people living on less than $1.90 a day on an international level&quot; (The World Bank, 2016), through the argument that the bourgeoisie (the upper class) are intent on exploiting the proletariat (the w', '', 'https://static.wixstatic.com/media/c7bda6_d290c0bb5c0e4bea8eaa8be7ed417799~mv2.png/v1/fill/w_1000,h_750,al_c,q_90,usm_0.66_1.00_0.01/c7bda6_d290c0bb5c0e4bea8eaa8be7ed417799~mv2.png', 'Yazmin Bleakley', ARRAY['Economic Geography & Marxism', 'Development Geographies']::TEXT[], '15 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('atlantropa-the-extraordinary-plan-to-dam-the-mediterranean', 'Atlantropa: The Extraordinary Plan to Dam the Mediterranean ', '', '2021-04-21T10:10:06.117Z', 'Introduction The 1920s are commonly known for being a time of economic and social prosperity in the west, propelled by wartime recovery and an economic boom. However, beneath this façade, instability and insecurity were rife. Since the first World War, over-population, unemployment, and lack of natural resources became a major problem in Europe (Vidal 2014), and difficulties with peace agreements, reparations and the US policy of non-interventionism created tension among nations which were still', '', 'https://static.wixstatic.com/media/c7bda6_6a440f3c8a7448b18959caf393ce70a4~mv2.jpg/v1/fill/w_770,h_620,al_c,q_85/c7bda6_6a440f3c8a7448b18959caf393ce70a4~mv2.jpg', 'Dónal Houston', ARRAY['Cultural & Historical Geography', 'Hydrology & Water Systems']::TEXT[], '7 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('a-critical-geographical-report-on-the-vostok-6-spaceflight', 'A Critical Geographical Report on the Vostok 6 Spaceflight', '', '2021-06-09T10:25:05.601Z', 'The Vostok space programme was a USSR initiative to put the first humans into space and return them safely to Earth (Kohonen, 2009). Vostok 6 was unique in that it established the first female cosmonaut, Valentina Tereshkova, in a space race renowned for being a masculine form of competition. In the words of Tereshkova, “A bird cannot fly with one wing only. Human space flight cannot develop any further without the active participation of women” (Uri, 2019, pp. 1). This would therefore imply tha', '', 'https://static.wixstatic.com/media/c7bda6_54b18bcb05bd42e18ad6701ce2c30d27~mv2.png/v1/fill/w_664,h_420,al_c,lg_1,q_85/c7bda6_54b18bcb05bd42e18ad6701ce2c30d27~mv2.png', 'Dion Hughes', ARRAY['Geographies of Outer Space', 'Cultural & Historical Geography']::TEXT[], '8 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('geopolitics-apocalypse-and-climate-change-an-interview-with-dr-tristan-sturm', 'Geopolitics, Apocalypse and Climate Change: An Interview with Dr Tristan Sturm', '', '2023-06-20T11:06:51.332Z', 'Last week, I had the pleasure of interviewing Dr Tristan Sturm, Senior Lecturer of Geography at Queen''s University, Belfast. In this interview, we discuss why Tristan believes Geography matters, his journey to becoming a Geography lecturer as well as his new and upcoming book projects. We also discuss the modules Tristan teaches throughout the Undergraduate Geography degree and Masters in Geopolitics here at QUB. Q1. Why do you think Geography matters and why should people study Geography?I woul', '', 'https://static.wixstatic.com/media/c7bda6_328db28f4ccb4d279ce78d23ce53556e~mv2.jpg/v1/fill/w_634,h_595,al_c,lg_1,q_85/c7bda6_328db28f4ccb4d279ce78d23ce53556e~mv2.jpg', 'Naomi Duncan-Todd', ARRAY['Political Geography & Geopolitics', 'Faculty Perspectives']::TEXT[], '8 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-effects-of-religious-segregation-and-deprivation-on-mental-health-a-peace-line-area-case-study', 'The Effects of Segregation and Deprivation in the Peace-Line Area of Belfast: Mental Health ', '', '2021-01-25T18:36:54.227Z', 'Residential segregation is usually measured based on the spatial distribution patterns of people who belong to specific groups e.g., religious or economic, where different communities don’t live or interact with each other (Boal, 1969). Northern Ireland has a unique form of segregation in the form of physical barriers known as ‘peace lines’, which can be seen in Figure 1. In the case of Belfast, they separate two different religiopolitical communities and were erected as a result of civil unrest', '', '', 'Julia Anusiak', ARRAY['Urban Geography & Segregation', 'Health & Medical Geography', 'Irish Landscapes']::TEXT[], '5 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('bowie-s-in-space-an-analysis-on-the-cultural-impact-of-david-bowie-s-career-on-outer-space', 'Bowie''s in Space: An Analysis on The Cultural Impact of David Bowie''s Career on Outer Space', '', '2021-02-12T14:36:59.856Z', 'The late David Bowie is a cultural icon, using imagery of the alien, unknown and space exploration to create a space for his career to flourish. In this essay, I will be analysing Bowie’s personas, namely Major Tom and Ziggy Stardust, and how they have attributed to our cultural understanding of outer space. Analysis of these personas will be through geographical theory, looking at imaginative geographies particularly, and contrasting the narrative of space and space exploration the presentation', '', '', 'Amy Oke', ARRAY['Geographies of Outer Space', 'Cultural & Historical Geography']::TEXT[], '11 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('how-does-climate-change-impact-biodiversity-in-the-great-barrier-reef', 'The Impact of Climate Change on Biodiversity in The Great Barrier Reef', '', '2021-02-24T10:00:19.620Z', 'ABSTRACTCoral reefs are a hub of biodiversity and are under threat with increasing temperatures causing mass bleaching events worldwide and increasing coral mortality. Observed historical temperatures from 1981-2010 were plotted alongside two future scenarios (2021-2050, 2071-2100) under two different RCP scenarios, RCP4.5 and RCP8.5 to predict future temperatures using the change factor method to downscale predictions from 2.5° x 2.5° to 0.5° x 0.5° to be comparable to the observed baseline dat', '', 'https://static.wixstatic.com/media/c7bda6_c4748e070d2f407fb28c4d06c060af60~mv2.jpg/v1/fill/w_800,h_599,al_c,q_85/c7bda6_c4748e070d2f407fb28c4d06c060af60~mv2.jpg', 'Sasha Wilson', ARRAY['Biogeography & Marine Ecology', 'Climate Change & Environmental Systems']::TEXT[], '14 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('not-all-men-but-too-many', 'Not All Men, But Too Many', '', '2021-03-14T14:43:49.459Z', '&quot;For a woman, daily life is dictated by the male gaze and the fear of male aggression. We avoid dark streets and empty parks. We grow up being told by our mothers and grandmothers how to smile politely after a cat-call so you aren’t followed home, how to walk and dress so that you fall into the periphery, how to become invisible as to be visible in a men’s world is to be a target. A threat. An “other” to their masculinity that challenges their artificial superiority in this milieu.&quot; - Anonymous ', '', 'https://static.wixstatic.com/media/c7bda6_c75a1bee04f34c3da1bb182f57fa453c~mv2.jpg/v1/fill/w_1000,h_463,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_c75a1bee04f34c3da1bb182f57fa453c~mv2.jpg', 'The Graticule', ARRAY['Feminist Geographies & Gender', 'Urban Geography & Segregation']::TEXT[], '26 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('in-place-out-of-place-geography-ideology-and-transgression-by-tim-cresswell', '''In Place/Out of Place (Geography, Ideology and Transgression)'', by Tim Cresswell', '', '2021-10-14T09:45:14.761Z', '&#010;‘In Place/Out of Place: Geography, Ideology and Transgression’ is written by Tim Cresswell, a cultural geography professor at Royal Holloway in London. Cresswell has been writing about place since as long as he has been a geographer (Cresswell, T., n.d), producing key literature in human geography e.g. ’Place: An Introduction’ (2014). However, the majority of his work is orientated more towards mobility; ‘On the move: Mobility in the modern western world.’ (2006), ''Geographies of mobilities: Pr', '', '', 'Jonathan Warke', ARRAY['Critical Spatial Theory', 'Cultural & Historical Geography']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('pristine-to-polluted-the-arctic-ocean-s-radioactive-predicament', 'Pristine to Polluted: The Arctic Ocean’s Radioactive Predicament ', '', '2023-09-12T13:54:19.314Z', 'In this article, Alysha Murray explains the importance of her undergraduate dissertation topic- Radioactive Pollution in the Arctic Ocean. ', '', 'https://static.wixstatic.com/media/c7bda6_167bac7563b3439b8c321ffd82ab81bf~mv2.jpg/v1/fill/w_864,h_486,al_c,lg_1,q_85/c7bda6_167bac7563b3439b8c321ffd82ab81bf~mv2.jpg', 'Alysha Murray', ARRAY['Climate Change & Environmental Systems', 'Physical Geography & Glaciology']::TEXT[], '11 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-outbreak-of-toxic-blue-green-algae-in-northern-ireland', 'The Outbreak of Toxic Blue-Green Algae in Northern Ireland', '', '2023-12-11T13:49:43.304Z', 'According to the Northern Ireland Environment Agency (NIEA, cited in BBC, 2023), there have been 168 confirmed reports of toxic blue-green algae in waterways across the province since May 2023. There is particular concern over Lough Neagh (Fig.1) which is the largest lake in the British Isles (Greene, 2023). The current levels of blue-green algae recorded in this lake have not been as high since the 1970s (Greene, 2023). This essay explores the causes of this harmful algal bloom and its threats ', '', 'https://static.wixstatic.com/media/c7bda6_1efb1e0176b6464cb1ca3436c5e00ccc~mv2.webp/v1/fill/w_976,h_549,al_c,q_85/c7bda6_1efb1e0176b6464cb1ca3436c5e00ccc~mv2.webp', 'Naomi Duncan-Todd', ARRAY['Hydrology & Water Systems', 'Irish Landscapes', 'Climate Change & Environmental Systems']::TEXT[], '4 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('acknowledging-polish-ethnicity-in-the-northern-ireland-census', 'Acknowledging Polish Ethnicity in the Northern Ireland Census', '', '2023-07-06T17:33:26.531Z', 'This article argues for the inclusion of Polish Ethnicity in the NI Census. ', '', 'https://static.wixstatic.com/media/c7bda6_d4077b89265949a2988a841ef97aa4d2~mv2.jpg/v1/fill/w_1000,h_500,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_d4077b89265949a2988a841ef97aa4d2~mv2.jpg', 'Aimee Kielt', ARRAY['Urban Geography & Segregation', 'Irish Landscapes']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-water-crisis-and-the-geopolitics-of-the-river-jordan', 'The Water Crisis and the Geopolitics of the River Jordan ', '', '2021-03-24T12:03:22.598Z', 'Introduction&#010;Over the last few decades, the impending doom of the &quot;water crisis&quot; and &quot;water wars&quot; have become an increasing concern to water professionals, political scientists, and media discourses. The dramatic statements of &quot;water crisis&quot; and &quot;water wars&quot; could become a realistic future, stemming from the simplistic belief that the availability of water across the world is limited and everlasting in terms of human use (Biswas, et al., 2019). This coupled with the drastic increase of populatio', '', 'https://static.wixstatic.com/media/c7bda6_fee0bb3f0bfa452d9af79516dc23969e~mv2.jpg/v1/fill/w_1000,h_667,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_fee0bb3f0bfa452d9af79516dc23969e~mv2.jpg', 'Shauna Vallely', ARRAY['Political Geography & Geopolitics', 'Hydrology & Water Systems']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('environmental-catastrophes-peatlands-climate-change-an-interview-with-professor-graeme-swindles', 'Environmental Catastrophes, Peatlands &amp; Climate Change: An Interview with Professor Graeme Swindles', '', '2023-09-13T10:58:47.638Z', 'Last week, I had the pleasure of interviewing Professor Graeme Swindles, Head of Geography, Archaeology and Paleoecology at Queen’s University Belfast. In this Interview, we discuss Graeme’s journey to become Head of Geography, life as a Geography Professor, as well his current, exciting research projects. We also touch on some of the modules Graeme teaches throughout the BSc in Geography and MSc in Climate Change here at QUB. Q1. Firstly, can you tell us about your journey and how you became He', '', 'https://static.wixstatic.com/media/c7bda6_66c9cb68b90140a5a2b1de87027595eb~mv2.jpg/v1/fill/w_619,h_720,al_c,q_85/c7bda6_66c9cb68b90140a5a2b1de87027595eb~mv2.jpg', 'Naomi Duncan-Todd', ARRAY['Climate Change & Environmental Systems', 'Faculty Perspectives']::TEXT[], '11 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('calculating-riverbank-erosion-sediment-and-nutrient-loading-rates-using-lidar', 'Calculating Riverbank Erosion, Sediment, and Nutrient Loading Rates using LiDAR', '', '2021-04-16T10:00:12.073Z', 'Riverbank erosion varies in its contribution to suspended sediment loads due to different contributing factors including climate, topography, geology, soils, and land usage (Thoma et al., 2005). Agricultural practises are suspected as the major contributing source to pollution for many waterways. As phosphorus is adsorbed to soil particles, this in combination with suspended sediment introduced through riverbank erosion, contributes to waterway degradation through eutrophication and sedimentatio', '', 'https://static.wixstatic.com/media/c7bda6_d4201321910b4ad581924d5982ad0e35~mv2.png/v1/fill/w_787,h_437,al_c,lg_1,q_85/c7bda6_d4201321910b4ad581924d5982ad0e35~mv2.png', 'Emma Hayes', ARRAY['Hydrology & Water Systems', 'Geographical Methods & Fieldwork']::TEXT[], '7 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('spatial-conformity-and-gender-a-ludonarrative-analysis-of-assassin-s-creed-liberation', 'Spatial Conformity and Gender: A Ludonarrative Analysis of Assassin’s Creed Liberation', '', '2021-02-03T10:00:11.896Z', 'Assassin’s Creed Liberation (2012) is renowned for being the first video game in the Assassin’s Creed franchise to have a woman as a playable protagonist. Naturally, this was the main selling point of the game, which was first released on the new PlayStation Vita system. The settings of the game are the Louisiana bayou, New Orleans city, Chitzen Itza in Mexico and briefly New York, set in the late 18th century. Aveline’s objective is to dismantle the oppressive control the Knights Templars have ', '', '', 'Dion Hughes', ARRAY['Feminist Geographies & Gender', 'Cultural & Historical Geography']::TEXT[], '14 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('has-trump-tramped-on-climate-change', 'Can Biden Undo Trump’s Fails in Battling Climate Change?', '', '2020-12-30T22:27:18.346Z', 'Scholars have argued that elites, such as presidents, can play a role in shaping beliefs of the mass public; is it possible that under Donald Trump’s presidency, his confidence in the spread of misinformation played a part in convincing people that climate change is a hoax?  Whilst we live in an age of ‘fact-checking’, and any fact thrown at the population by a public figure can be immediately debunked (Porter et. al., 2019), is it possible that some of Trump’s supporters still choose to ignore ', '', 'https://static.wixstatic.com/media/c7bda6_52c19af8e2594428a67ccda7cc2e8e9e~mv2.jpg/v1/fill/w_1000,h_667,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_52c19af8e2594428a67ccda7cc2e8e9e~mv2.jpg', 'Julia Anusiak', ARRAY['Political Geography & Geopolitics', 'Climate Change & Environmental Systems']::TEXT[], '3 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('famous-geographers-isabella-bird-bishop-frgs', 'Famous Geographers: Isabella Bird Bishop, FRGS', '', '2021-03-17T10:19:10.594Z', 'This article aims to critically investigate the contributions to geography made by prolific photojournalist ‘lady traveller’ Isabella Bird, situated within the zenith of the Age of Exploration (The Times, 1904; Middleton, 1973; Porter and Low, 1999). As one of the world’s principal states, Britain was an expanding colonial power during the eighteenth-twentieth centuries and actively encouraged its citizens to travel across its growing territories (Morin, 1998; Porter and Low, 1999). Bird was enc', '', 'https://static.wixstatic.com/media/c7bda6_0179d8ec97d64058a532e45bba948d4c~mv2.jpg/v1/fill/w_583,h_458,al_c,lg_1,q_80/c7bda6_0179d8ec97d64058a532e45bba948d4c~mv2.jpg', 'Emilia Coady-Booth', ARRAY['Cultural & Historical Geography', 'Feminist Geographies & Gender']::TEXT[], '15 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('labour-exploitation-within-global-production-networks-who-is-to-blame', 'Labour Exploitation within Global Production Networks: Who is to Blame?  ', '', '2024-02-29T13:45:41.925Z', 'This article examines where responsibility resides for labour exploitation within Global Production Networks', '', 'https://static.wixstatic.com/media/c7bda6_d3870b69edda42e480c994b9eda559e9~mv2.png/v1/fill/w_1000,h_682,al_c,q_90,usm_0.66_1.00_0.01/c7bda6_d3870b69edda42e480c994b9eda559e9~mv2.png', 'Naomi Duncan-Todd', ARRAY['Economic Geography & Marxism', 'Development Geographies']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('earth-cosmos-and-culture-an-interview-with-dr-oliver-dunnett', '''Earth, Cosmos and Culture'': An Interview with Dr Oliver Dunnett', '', '2021-05-26T10:00:44.870Z', 'Earlier this month, our lead editor - Amy Oke, had the pleasure of talking with Dr Oliver Dunnett about his new book ''Earth, Cosmos and Culture: Geographies of outer-space in Britain 1900 - 2020''. Dr Dunnett is currently teaching at Queen''s University Belfast and is Chair of the Royal Geographic Society for the Northern Ireland Branch. He has an interest in political, historical, and cultural geography and is one of the leading researchers in geographies of outer space.Dr Oliver Dunnett''Earth, C', '', 'https://static.wixstatic.com/media/c7bda6_793baaa36c6a4a1b92f411830bceaabc~mv2.jpg/v1/fill/w_1000,h_667,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_793baaa36c6a4a1b92f411830bceaabc~mv2.jpg', 'Amy Oke', ARRAY['Geographies of Outer Space', 'Faculty Perspectives']::TEXT[], '9 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('so-what-exactly-is-feminism-a-brief-history', 'So, What Exactly is Feminism? - A Brief History', '', '2021-06-02T12:41:06.312Z', 'Author''s Note:As a disclaimer, this article is in no way meant to be of an academic standard; whilst I have used referencing throughout it, I have also relied on websites and Wikipedia for information. As a result, I apologise if anything I have written is slightly incorrect and if you''re a lecturer or academic, please don''t kill me for using Wiki :)OriginsFeminism as we know it did not become a thing until the 19th century, that does not mean however that it did not exist before that.In ''Republ', '', 'https://static.wixstatic.com/media/c7bda6_477d8d89e262458da7127b0ff3d592cb~mv2.jpeg/v1/fill/w_1000,h_563,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_477d8d89e262458da7127b0ff3d592cb~mv2.jpeg', 'Julia Anusiak', ARRAY['Feminist Geographies & Gender']::TEXT[], '13 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('digital-geographies-the-representation-of-apocalypse-in-videogame-landscapes', 'Digital Geographies: The Representation of Apocalypse in Videogame Landscapes', '', '2024-04-19T13:32:43.191Z', 'PhD student, Megan O''Kane gives us a brief overview of her dissertation project on how apocalypse is represented in videogame landscapes. ', '', 'https://static.wixstatic.com/media/c7bda6_1c2c6f20032d4786a1e898db1bd2c140~mv2.jpg/v1/fill/w_923,h_524,al_c,q_85/c7bda6_1c2c6f20032d4786a1e898db1bd2c140~mv2.jpg', 'Megan O''Kane', ARRAY['Cultural & Historical Geography', 'Critical Spatial Theory']::TEXT[], '6 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-geopolitics-of-blood-diamonds-in-sierra-leone', 'The Geopolitics of Blood Diamonds in Sierra Leone', '', '2021-04-14T08:29:39.853Z', 'The former British colony of Sierra Leone appeared to have a stable political system around the time of their independence in 1961 (Clapham, 2003). The formal collapse of the state occurred in 1991 but Sierra Leone was not an obvious contender for such a collapse. Nevertheless, the political economy suffered, and the war persisted. From the 1950s to the 1970s resource wealth dominated the ideological discussion of development scholars and Marxist and non-Marxist critics (Ross, 1999). Resource co', '', 'https://static.wixstatic.com/media/c7bda6_dafb110c41c44b3da7f02c4051e7eabf~mv2.png/v1/fill/w_420,h_631,al_c,lg_1,q_85/c7bda6_dafb110c41c44b3da7f02c4051e7eabf~mv2.png', 'Eliza O''Gorman', ARRAY['Political Geography & Geopolitics', 'Economic Geography & Marxism']::TEXT[], '12 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('behind-the-scenes-of-qub-geography-a-brief-interview-with-jim-sloan', 'Behind The Scenes of QUB Geography: A Brief Interview with Jim Sloan  ', '', '2024-02-08T19:08:07.706Z', 'Jim tells us about his role as a technician within the geography department at QUB and the importance of his work for students and staff', '', 'https://static.wixstatic.com/media/c7bda6_bb8c3f508f6c4394b330ff03b3a79a06~mv2.jpg/v1/fill/w_280,h_280,al_c,lg_1,q_80/c7bda6_bb8c3f508f6c4394b330ff03b3a79a06~mv2.jpg', 'The Graticule', ARRAY['Student Dispatches', 'Faculty Perspectives']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('an-interview-with-professor-nuala-c-johnson-mria', 'An Interview with Professor Nuala C Johnson, MRIA', '', '2021-03-19T15:09:14.211Z', 'Editors Dion Hughes and Sasha Wilson had the amazing opportunity to interview Professor Nuala Johnson, who was kind enough to find the time to allow this interview. Professor Johnson joined Queen''s University Belfast in 1996 and retired earlier this year; she is a historical and political geographer and taught and influenced us all over the last few years. In this interview, Dion and Sasha discuss Professor Johnson''s career, her future plans, and any advice she would give to those embarking on t', '', '', 'The Graticule', ARRAY['Cultural & Historical Geography', 'Faculty Perspectives']::TEXT[], '12 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('human-geography-made-simple-marxism', 'Human Geography Made Simple: Marxism', '', '2021-04-28T10:00:21.032Z', 'Marxism, in simple terms, is a type of socialism derived from Karl Marx’s teachings, which aims to reduce or abolish the injustice and inequality caused by capitalism (Daniels et. al., 2016). It focuses on the injustices and oppression posed on the proletariat: the workers, by the bourgeoisie. Further, it aims for “political commitment to social transformation” (Gregory et. al., 2009:246)Marx outlined that a society is split into two antagonistic social classes: the bourgeoisie (the capitalists)', '', 'https://static.wixstatic.com/media/c7bda6_c37fa4ef48374ddeaf71897627142006~mv2.jpeg/v1/fill/w_1000,h_666,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_c37fa4ef48374ddeaf71897627142006~mv2.jpeg', 'Julia Anusiak', ARRAY['Economic Geography & Marxism', 'Critical Spatial Theory']::TEXT[], '1 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('book-review-gender-identity-and-place-understanding-feminist-geographies-by-mcdowell-l-1999', '''Gender, Identity and Place: Understanding Feminist Geographies'' by McDowell, L. (1999)', '', '2021-02-19T11:31:55.048Z', '“Gender, Identity and Place Understanding Feminist Geographies” seeks to depict gendered issues with regards to a feminist-geographical perspective. Linda McDowell states: “My aim is to outline some of the main connections between geographical perspectives and feminist approaches and to illustrate them with empirical work that I have read and enjoyed over the last few years” (pg. viii). Whilst reading McDowell’s book it was clear she was focused on portraying gendered issues with a geographical ', '', 'https://static.wixstatic.com/media/c7bda6_bb166316df7d469581d4685eb3a864ff~mv2.jpg/v1/fill/w_1000,h_1000,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_bb166316df7d469581d4685eb3a864ff~mv2.jpg', 'Dion Hughes', ARRAY['Feminist Geographies & Gender', 'Critical Spatial Theory']::TEXT[], '12 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('investigating-icelandic-lava-tubes-a-day-in-the-life-of-a-geography-dissertation-project', 'Investigating Icelandic Lava Tubes: A Day in the Life of a Geography Dissertation Project', '', '2023-07-14T13:17:21.031Z', 'I am Ciara,  I just graduated with my BSc degree in Geography with French at QUB and I wanted to share my experience undertaking fieldwork as part of my final year geography dissertation project. My work involved investigating Icelandic lava tubes as analogues for Lunar and Martian lava tubes to assess habitability.  I was delighted with the opportunity to undertake a research trip to Iceland for my work in August 2022, with help from The QUB Sir Thomas Dixon Travel Scholarship. This allowed me ', '', 'https://static.wixstatic.com/media/c7bda6_6c5c843c6d4c40019f337140dbbc0110~mv2.jpg/v1/fill/w_823,h_531,al_c,q_85/c7bda6_6c5c843c6d4c40019f337140dbbc0110~mv2.jpg', 'Ciara McKnight', ARRAY['Physical Geography & Glaciology', 'Geographical Methods & Fieldwork']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('mapping-glacial-geomorphology-in-iceland-an-overview-of-a-phd-dissertation-project', 'Mapping Glacial Geomorphology in Iceland: An Overview of a PhD Dissertation Project.  ', '', '2023-11-02T12:07:54.410Z', 'I am Amy Lally, a fourth year QUADRAT PhD student in Geography. My research study site is Breiðamerkurjökull, an outlet glacier on the southside of the Vatnajökull ice cap (Figure 1). I have been lucky enough to undertake four field trips to this incredible glacier during my project so far. Unfortunately, like all other glaciers around the world it is thinning and retreating at unprecedented rates in response to human induced climate change with retreat rates of up to 500 m since the start of my', '', 'https://static.wixstatic.com/media/c7bda6_033d8b164ad24ac0b7fb49a282a4f5b4~mv2.jpg/v1/fill/w_1000,h_614,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_033d8b164ad24ac0b7fb49a282a4f5b4~mv2.jpg', 'Amy Lally', ARRAY['Physical Geography & Glaciology', 'Geographical Methods & Fieldwork']::TEXT[], '3 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('human-geography-made-simple-utopian-geographies', 'Human Geography Made Simple: Utopian Geographies ', '', '2021-11-11T10:15:02.467Z', 'The idea of ‘utopia’ in geographical thinking was first explored by Thomas More (1516), in fact More coined the term ‘utopia’ (Vieira, 2010) when imagining a perfect island where both pristine beaches and flawless cities existed, as well as societal equality - of sorts. Influential to imaginative geography as More was, he didn’t create the notion of longing for a better world, only the more tangible expression of that longing. (Vieira, 2010) Utopia has since been defined as “an ideal society, st', '', 'https://static.wixstatic.com/media/c7bda6_7e5ede05e54e4195ae41843e426876af~mv2.png/v1/fill/w_762,h_1000,al_c,q_90,usm_0.66_1.00_0.01/c7bda6_7e5ede05e54e4195ae41843e426876af~mv2.png', 'Jonathan Warke', ARRAY['Critical Spatial Theory', 'Cultural & Historical Geography']::TEXT[], '3 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('geoforensics-with-dr-alastair-ruffell', 'Geoforensics with Dr Alastair Ruffell ', '', '2024-01-22T16:12:35.038Z', 'In this article, Dr Ruffell tells us all about Geoforensics at QUB and the fascinating cases that he has worked on over the years. ', '', 'https://static.wixstatic.com/media/c7bda6_834686ce10e349b998df71bc4aa75208~mv2.png/v1/fill/w_799,h_597,al_c,q_90/c7bda6_834686ce10e349b998df71bc4aa75208~mv2.png', 'Naomi Duncan-Todd', ARRAY['Geographical Methods & Fieldwork', 'Faculty Perspectives']::TEXT[], '12 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('is-it-realistic-for-developing-states-to-grow-without-reliance-on-fossil-fuels', 'Is it Realistic for Developing States to Grow Without Reliance on Fossil Fuels? ', '', '2022-02-10T11:17:36.516Z', 'INTRODUCTIONThe above thesis question will further aim to address the burden of change that is posed on underdeveloped countries, with India as a case study. Highlighting the lack of support given by MEDC’s, as well as blame-shifting, lack of accountability and expectance to ‘learn from past mistakes’, regarding the use of fossil fuels and carbon emissions. LITERATURE REVIEWA plethora of literature discusses the world’s reliance on fossil fuels, such as that of Idundun et. al, (2019), which disc', '', 'https://static.wixstatic.com/media/c7bda6_06edc57b5ee64073bd1d951c0b667459~mv2.png/v1/fill/w_1000,h_575,al_c,q_90,usm_0.66_1.00_0.01/c7bda6_06edc57b5ee64073bd1d951c0b667459~mv2.png', 'Julia Anusiak', ARRAY['Development Geographies', 'Climate Change & Environmental Systems']::TEXT[], '13 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('human-geography-made-simple-neoliberalism', 'Human Geography Made Simple: Neoliberalism ', '', '2021-03-26T12:36:08.181Z', 'Neoliberalism ideology claims that a free market economy provides the ultimate free choice and allows for optimum economic growth of state (Kotz, 2002); it focuses on the belief that state intervention in economic development leads to inefficiencies, as their incentives often result in the ''economy''s winners'' getting punished, and the ''losers'', getting rewarded. In simple terms, it believes that the government should have nothing to do with the market, and that free markets should be able to reg', '', 'https://static.wixstatic.com/media/c7bda6_1e095287c4024fafb56231db5d899f63~mv2.png/v1/fill/w_1000,h_648,al_c,q_90,usm_0.66_1.00_0.01/c7bda6_1e095287c4024fafb56231db5d899f63~mv2.png', 'The Graticule', ARRAY['Economic Geography & Marxism', 'Critical Spatial Theory']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('predicting-climate-change', 'Predicting Climate Change ', '', '2021-02-15T17:17:05.504Z', 'For a long time, it has been argued that in order to understand the potential climate change in the future, we need to understand why and how climate change occurred in the past. We source information on past climates through paleoclimatic reconstruction, which aids our present climate change models and helps give us a better understanding of what could happen in the future (Skinner, 2008).  Equally, predictions are and have always been uncertain; the extent of anthropogenic factors of climate c', '', 'https://static.wixstatic.com/media/c7bda6_3d23957a839d4cf0b62af3c67fe2e8b3~mv2.jpg/v1/fill/w_1000,h_661,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_3d23957a839d4cf0b62af3c67fe2e8b3~mv2.jpg', 'Julia Anusiak', ARRAY['Climate Change & Environmental Systems', 'Physical Geography & Glaciology']::TEXT[], '5 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('over-and-beyond-the-bridge-of-sighs-a-local-perspective-of-cambridge', 'Over and Beyond the Bridge of Sighs: A Local Perspective of Cambridge', '', '2021-02-25T00:00:00.000Z', 'When people ask me where I’m from and hear “Cambridge'''', the reactions are mostly along the lines of, “Oooo, you’re posh”. It is normal, expected even, to make such assumptions, however, in my experience, these stereotypes are not strictly true. Yes, we have fancy buildings and expensive universities. It is even correct to say we home a good few of the most wealthy people in the country. However, we are also just like any other city. Our streets home the homeless, the majority of our people are ', '', 'https://static.wixstatic.com/media/c7bda6_01d9a5852e1f4d5ea09a5b4026ee5161~mv2.jpg/v1/fill/w_800,h_1000,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_01d9a5852e1f4d5ea09a5b4026ee5161~mv2.jpg', 'Martha Roney', ARRAY['Urban Geography & Segregation', 'Cultural & Historical Geography']::TEXT[], '2 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('final-year-geography-a-week-in-the-life', 'Final Year Geography: A Week in the Life ', '', '2025-09-26T10:19:27.683Z', 'In this article, our Lead Editor, Naomi Duncan-Todd brings you along with her for the first week back at university. ', '', 'https://static.wixstatic.com/media/c7bda6_3e43943a5700465c9c6fdda8a28425ff~mv2.png/v1/fill/w_692,h_468,al_c,lg_1,q_85/c7bda6_3e43943a5700465c9c6fdda8a28425ff~mv2.png', 'Naomi Duncan-Todd', ARRAY['Student Dispatches']::TEXT[], '4 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('the-global-landscape-a-photography-series', 'The Global Landscape: A Photography Series ', '', '2023-06-06T11:11:56.186Z', 'This photography series showcases the beauty of our natural and built environment across the world. ', '', 'https://static.wixstatic.com/media/c7bda6_93604bd83a864d82afb502c27c1faa09~mv2.jpg/v1/fill/w_1000,h_750,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_93604bd83a864d82afb502c27c1faa09~mv2.jpg', 'Naomi Duncan-Todd', ARRAY['Cultural & Historical Geography', 'Visual Geography']::TEXT[], '1 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
INSERT INTO posts (slug, title, subtitle, date, excerpt, content, cover_image, author, categories, read_time) VALUES ('a-day-in-the-life-of-a-third-year-geography-student', 'A Day in the Life of A Third Year Geography Student ', '', '2021-05-19T12:00:43.929Z', 'The Graticule''s first video submission - Sasha Wilson, a third-year undergraduate BSc Geography student shows you a day in her life. ', '', 'https://static.wixstatic.com/media/c7bda6_518e611f3bab4ae99b0adc48294771b0~mv2.jpeg/v1/fill/w_1000,h_750,al_c,q_85,usm_0.66_1.00_0.01/c7bda6_518e611f3bab4ae99b0adc48294771b0~mv2.jpeg', 'Sasha Wilson', ARRAY['Student Dispatches']::TEXT[], '1 min read') ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content, cover_image = EXCLUDED.cover_image, author = EXCLUDED.author, categories = EXCLUDED.categories, read_time = EXCLUDED.read_time;
